notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: "Yt0Ijy0QdExY9wWPCPCIr/yuNtDkPh/KJ9UGUE84jFlBQO8URpK2MSOjSdAmbB4Vu0HdjtFOO3fHBZqYiMYNVHRs0jlXyux68VKcQ6rwihN+MYAmiov6tSstwlJCIq1iTnx3UHHMdkQrkSgFeOcLMZLq7RCXVUyFIleqYXL4ynZhsgCE6bunQ4xfKPmHR87lKfEjHdPF7OK2LTP9BeJhNX8WzPPSwCVSEoCPNnY6w4RtmVs5kNNbCxN13WJOnGUUJ/MuDgzmjlN7vbE3/uVZwxb2QlGf4xt0SveCwYkEsXatFqA1n8evFsU3ZqP3pBZPynKTxtjusJHJ0Q3VRsykVhH4575r7oNiT4unlUU3+GHPh37p2tBNzUvBzuDKtUBc/ixWVmioiyQuO6dFYyTq8TjCtUMFuZs4GxBBNTRNiWnKyORNOkoH/YT1BKdXro7Qo7Dk4WpSC+N/YnpJ4K1a5WVCyuo15QaOeXXA8IsPSyIxqkD6bhYR1YR5ZW7f1gmq1AeSCrEs7gozgzZSs7Q3+2fJrGf3AfiwcA+IroYbUmn8ANOMfiVP/MnQxH3dU+1qsvS8/4YZO+Qsd9qZ7p7HdedZMUVBWj3mh/UsI+ZY7egPMAzX6+qEyL+pnT1EDPkfFyyQf02sZHVUaLAgV8MhKyS1A7z9pehF3giWJpVacAg="
language: node_js
node_js:
  - "4.2"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g strongloop
  - npm install -g mocha
install: npm install
