notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      - secure: "B4sYke/Kq8ADz67wcz3CJ3m6Wv5bbxUvKXCKxRpZZRWZLVjwVpFvsfzrJvvDmbzedMZbTGb+RWtg+myvLRUUlqKmbjb3omTkEEvwio2S3/HDqSidnaiyc+devnynmCR43Xp3eMItvek13trwFQGLNoVR1wp9r0YRubCr2Iu1DiWcJJunSsVuVD8lXSQMpZ0WUtD/Tgz2RUn1MmjYhPLw9OtCzKNcA+QZguiBDCWf07L03OECsfBsEz9X+ZSceAaaDmOR6kfOoSB4+olrkqasRYSScuPd1jics/t4bHfJCN9eAUKRQt4z8quuPx+RCO6NRHNZogFZZLP4cw8XXcZncWaKc9zOAvBjJotUFqgHua1AFeTfYc+DdXtK0LB53JNP+CWpYX7tckDAr0B4E8vMd7DYKGs1d9QwC+YpJwHSfgMup2uCwxSRbxaZOudiCFIR1xfeNIR216iJov/7E8d0i+5cMCG5khQE0S/aFKSbIBuz3nncExOvK8QW9HdcC+nQkrswuIi/YvBHcXgzEJuL+EXMmPU0xuZ5+ZSNLKP93x2/2F+D6Ys9o/fg8ppK9AIUeHYYmvOZzGHxNak+dK/lyGToKSDRQ/zEW2XXSHnpFK1C7AgNeRO+Aj5y3c4fNA35L2QuYQRmKDtGuXSez5yDLs5FbVQE2mhfZ/JjzM3JOLc="
      - secure: "dsDm023h0eWFgf9xnU2HLao1mwqMESV1oVq8IWRSdWferSoaC5OUWdM8fPPl/QoZkKZrpPEtj733/4SjvPqg2BePQZFsgJZJjnwGt4sK9DDwvcNZAu2y+jC+toCXMvOYoTVPEpcCw9ce27GH9FgxKBl6UohN4MfkCTZkvfyJvREtX5ARuLGPKkDdOiFwYRtgTJ4pOMgxmN8cybmxCeBIoI2nVn2oyhALRKPvVlWJE1AnNigptsEbMjHpbyTjuRC0stB7inHj+avstzz/ODSXi/aYEbkDbHa2gu8tNYstQO5PJFzL1nwWyFlRhvWfMXoru+Lv3s+XVgcwCqIuDjLMy9vNULLme0ZbzsH9KmPiue5N+8p+8TCXPVhfMP/70A/ecRmPVXNuhIAZ+FHWjfUWUx0RAMV7zJDOM8tamcvEv5NO/+Y2e2/jQFczMqTB0mGVjIqV7vbK6sKtnNO0brJwIWWMf+e0K0vu6HrEAEtnywVplTbUY7owFMNfZaoYL1aqREqDnhuOiGJ47TOT8beD9OQ9jyPNJUpOFhVp3IuUrHDGOstsf+1qyAIT0obPu//SCIZU7BHo7Dkyp75mcZJoYEpX7Lj6jOSlcZ+wMVRljQV/Noj1tdG7EPJPJj2wiUyO4dBMp5STk431cYNsLVWIIhvTHVn1F7E1p4ugRlmdMrY="
language: node_js
node_js:
  - "4.2"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g strongloop
  - npm install -g mocha
install: npm install
